# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170929_0013'),
        ('orders', '0005_auto_20181108_0659'),
    ]

    operations = [
    ]
