# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181030_1934'),
        ('products', '0009_product_timestamp'),
        ('products', '0008_auto_20181031_1526'),
    ]

    operations = [
    ]
