# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-05 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestap',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updates',
            new_name='updated',
        ),
    ]
